const { Skills } = require("../models");

const data = [
  {
    title: "Wonder Explorers",
    subtitle: "Embark on an Exciting Journey of Discovery!",
    description: "Calling all young adventurers! Join the Wonder Explorers and set out on an extraordinary journey to uncover the secrets of the world around us. From the mysteries of space to the wonders of nature, each lesson will immerse you in a different topic. Dive deep into the ocean, unravel ancient civilizations, explore the vastness of the universe, and encounter fascinating creatures. Through interactive games, captivating stories, and hands-on experiments, you'll develop a deep understanding of diverse subjects and cultivate a lifelong love for learning. Expand your horizons and become a true Wonder Explorer. Enroll now and let the adventure begin!",
    image_url: "/images/explore.jpg",
    price: "99.99",
    place: "Subiaco, WA",
    address: "123 Wellingtoon St, Subiaco, WA",
    contact: "(08)12345678",
    start_date: "2023-06-15",
    end_date: "2023-06-30",
    difficulty_rating: "Intermediate",
    background_color: "#46ff96",
  },
  {
    title: "Science Explorers",
    subtitle: "Embark on a Thrilling Journey through the World of Science!",
    description: "Attention young scientists! Join the Science Explorers and embark on an exhilarating journey through the wonders of science. From uncovering the secrets of the human body to exploring the mysteries of the natural world, this course will ignite your curiosity and deepen your understanding of scientific concepts. Conduct hands-on experiments, unravel scientific mysteries, and engage in interactive activities that will spark your love for discovery. Whether it's delving into the realms of chemistry, biology, or physics, you'll develop critical thinking skills and a passion for scientific exploration. Enroll now and let the adventure of scientific discovery begin!",
    image_url: "/images/science.jpg",
    price: "99.99",
    place: "Perth, WA",
    address: "456 Wellington Lane, Perth, WA",
    contact: "(08)12345678",
    start_date: "2023-06-15",
    end_date: "2023-06-30",
    difficulty_rating: "Advanced",
    background_color: "#ff9898",
  },
  {
    title: "ABC Adventure",
    subtitle: "Explore the Alphabet in an Exciting Learning Journey!",
    description: "Welcome to ABC Adventure, a captivating course that will take you on a magical journey through the world of letters! Join our friendly characters as they guide you through interactive games, delightful stories, and engaging activities that will help you learn the ABCs. From meeting adorable animals to uncovering hidden letter treasures, each step of this adventure will deepen your understanding of the alphabet. Get ready to sing, play, and explore as you unlock the secrets of reading and writing. Enroll now and embark on a joyful ABC learning experience!",
    image_url: "/images/abc.png",
    price: "89.99",
    place: "Fremantle, WA",
    address: "789 Wellington Avenue, Fremantle, WA",
    contact: "(08)12345678",
    start_date: "2023-06-15",
    end_date: "2023-06-30",
    difficulty_rating: "Easy",
    background_color: "#87c0fc",
  },
  {
    title: "Math Magic",
    subtitle: "Become an Addition Wizard and Master Math Magic",
    description: "Calling all young adventurers! Join our team of Math Marvels on an exciting Addition Expedition! Step into a world where numbers come alive and learn the secrets of addition through captivating activities. Dive into thrilling challenges, solve puzzles, and conquer interactive games that will sharpen your addition skills. From counting colorful treasures to solving tricky math riddles, this course will ignite your passion for numbers. Gain confidence as you unlock new levels and earn rewards along the way. Are you ready to become an Addition Expert? Enroll today and unleash your mathematical superpowers!",
    image_url: "/images/addition.png",
    price: "79.99",
    place: "Belmont, WA",
    address: "101 Number Avenue, Belmont, WA",
    contact: "(08)12345678",
    start_date: "2023-06-15",
    end_date: "2023-06-30",
    difficulty_rating: "Easy",
    background_color: "#fff8ad",
  },
  {
    title: "Subtraction Safari",
    subtitle: "Embark on an Exciting Math Expedition!",
    description: "Welcome to Subtraction Safari, where math becomes an exhilarating adventure! Join our fearless explorers as they venture into the realm of subtraction. Through thrilling games, engaging puzzles, and interactive activities, you'll develop a strong foundation in taking away numbers. Dive into captivating challenges like counting backward, solving subtraction riddles, and discovering the hidden treasures of subtraction. Gain confidence in subtraction concepts such as regrouping and borrowing while having a blast. Get ready to become a Subtraction Master and unlock the power of numbers! Enroll in Subtraction Safari today and let the expedition begin!",
    image_url: "/images/subtraction.png",
    price: "79.99",
    place: "Perth, WA",
    address: "202 Number Avenue, Perth, WA",
    contact: "(08)12345678",
    start_date: "2023-06-15",
    end_date: "2023-06-30",
    difficulty_rating: "Easy",
    background_color: "#ffa768",
  },
  {
    title: "Creative Writing Wizards",
    subtitle: "Embark on a Magical Journey into the World of Creative Writing!",
    description: "Calling all aspiring writers! Join the Creative Writing Wizards and embark on a magical journey into the realm of storytelling and imagination. Explore the art of crafting captivating characters, creating vivid settings, and weaving spellbinding plots. Through engaging writing prompts, interactive exercises, and constructive feedback, you'll unleash your creativity and develop your unique writing voice. Dive into different genres, from fantasy to mystery, and learn essential writing techniques that will bring your stories to life. Whether you dream of becoming a novelist or simply want to express yourself through writing, this course will empower you to become a true Creative Writing Wizard!",
    image_url: "/images/writing.jpg",
    price: "99.99",
    place: "Perth, WA",
    address: "303 Story Lane, Perth, WA",
    contact: "(08)12345678",
    start_date: "2023-06-15",
    end_date: "2023-06-30",
    difficulty_rating: "Advanced",
    background_color: "#fc5bff",
  },
  {
    title: "Poetry Perfection",
    subtitle: "Unlock the Power of Words through Beautiful Poetry",
    description: "Discover the enchanting world of poetry and master the art of crafting beautiful verses. In this immersive course, you'll explore various poetic forms, from sonnets to haikus, and learn techniques to evoke emotions and create vivid imagery with your words. Through engaging writing exercises and in-depth analysis of renowned poets, you'll refine your writing style and develop your unique poetic voice. Whether you're a beginner or an experienced writer, this course will empower you to express yourself through the power of poetry.",
    image_url: "/images/poetry.jpg",
    price: "79.99",
    place: "Bunbury, WA",
    address: "404 Poet Street, Bunbury, WA",
    contact: "(08)12345678",
    start_date: "2023-06-15",
    end_date: "2023-06-30",
    difficulty_rating: "Intermediate",
    background_color: "#ffa500",
  },
  {
    title: "Journalism 101",
    subtitle: "Become a Skilled Investigative Journalist",
    description: "Unleash your passion for truth and justice with Journalism 101. This comprehensive course will equip you with the skills and knowledge to become a skilled investigative journalist. Learn the art of conducting interviews, gathering reliable sources, and crafting compelling news articles. Dive into the world of investigative reporting, uncover hidden stories, and shed light on important issues. With hands-on assignments and real-world scenarios, you'll develop the critical thinking and storytelling abilities needed to make a difference through journalism.",
    image_url: "/images/journalism.jpg",
    price: "129.99",
    place: "Perth, WA",
    address: "505 News Avenue, Perth, WA",
    contact: "(08)12345678",
    start_date: "2023-06-15",
    end_date: "2023-06-30",
    difficulty_rating: "Advanced",
    background_color: "#00FF00",
  },
  {
    title: "Fun and Games Galore",
    subtitle: "Discover a World of Fun and Adventure!",
    description: "Calling all kids! Join us for a thrilling adventure filled with fun and games. In this interactive course, you'll engage in exciting activities that will spark your imagination and keep you entertained. From arts and crafts to outdoor games and team challenges, you'll explore a wide range of activities that promote creativity, problem-solving, and teamwork. Get ready to make new friends, learn new skills, and create unforgettable memories. Join us on this amazing journey and let the fun begin!",
    image_url: "/images/kids-fun.jpg",
    price: "49.99",
    place: "Perth, WA",
    address: "606 Kids Street, Perth, WA",
    contact: "(123) 456-7890",
    start_date: "2023-08-01",
    end_date: "2023-08-15",
    difficulty_rating: "Easy",
    background_color: "#b1cbbb",
  },
  {
    title: "Photography Fundamentals",
    subtitle: "Capture Moments, Create Memories, and Unleash Your Creativity",
    description: "Discover the fascinating world of photography and learn to capture breathtaking images that tell powerful stories. In this comprehensive course, you will delve into the fundamentals of photography, including composition, lighting, exposure, and post-processing techniques. Whether you're a beginner or an aspiring professional, this course will equip you with the skills and knowledge to express your unique perspective through stunning photographs. Explore different genres, from landscape to portrait photography, and gain hands-on experience through engaging assignments and practical exercises. Unleash your creativity and embark on a visual journey that will transform your passion for photography into a lifelong pursuit.",
    image_url: "/images/photography.jpg",
    price: "149.99",
    place: "Wanneroo, WA",
    address: "707 Shutter Lane, Wanneroo, WA",
    contact: "(123) 456-7890",
    start_date: "2023-07-15",
    end_date: "2023-08-15",
    difficulty_rating: "Intermediate",
    background_color: "#48cae4",
  }
];


const seedSkills = () => Skills.bulkCreate(data);

module.exports = seedSkills;
